

# This file was *autogenerated* from the file carter1968/field_strength.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)# 4-dimensional manifold:
M = Manifold(_sage_const_4 , 'M')
U = M.open_subset('U')
chart = U.chart(names=('λ', 'μ', 'ψ', 'χ',)); (λ, μ, ψ, χ,) = chart._first_ngens(4)
eU = chart.frame() 
var('e alpha')  # e と α を定数として扱う
def show_field_strength(A):
    print(A.display(eU)) # 微分形式 a を表示
    print(A.exterior_derivative().display(eU))
# Differential form of degree 1 on M
# Define the four-potential
A_typeA = M.diff_form(_sage_const_1 , name='A_A')
A_typeB = M.diff_form(_sage_const_1 , name='A_B')
A_typeC = M.diff_form(_sage_const_1 , name='A_C')
A_typeD = M.diff_form(_sage_const_1 , name='A_D')

# 微分形式の成分を設定
A_typeA[eU, :] = [_sage_const_0 , _sage_const_0 ,
    e * λ * μ * (μ * cos(alpha) + λ * sin(alpha)) / (λ**_sage_const_2  + μ**_sage_const_2 ),
    e * (λ * cos(alpha) - μ * sin(alpha)) / (λ**_sage_const_2  + μ**_sage_const_2 )]
show_field_strength(A_typeA)

A_typeD[eU, :] = [_sage_const_0 , _sage_const_0 , e * λ * cos(alpha), - e * μ * sin(alpha)]  # 成分を指定
# show_field_strength(A_typeD)

